# For advanced use and comprehensive documentation of the format, please see:
# https://docs.haskellstack.org/en/stable/yaml_configuration/

# please update the docker image tag in `.circleci` when changing the resolver
resolver: lts-13.25

packages:
  - '.'

extra-deps:
  - dhall-1.24.0
  - endo-0.3.0.1
  - verbosity-0.3.0.0
  - git: https://github.com/trskop/host-and-port.git
    commit: f4639d63f5c2e4c4faef94f5214111625af2a85d
  - git: https://github.com/trskop/mainplate.git
    commit: 118acdb919e7bd7aaa07e7554a2d1eabde86acf5

flags: {}
# verbosity:
#   dhall: true

system-ghc: true
